networks:
  rabbitmq_net:
    name: rabbitmq_net
    driver: bridge
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: "nginx-proxy"
    networks:
      - rabbitmq_net
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./certs:/etc/nginx/certs"
      - "./vhost:/etc/nginx/vhost.d"
      - "./html:/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    # environment:
    #   - DEFAULT_HOST=nost.smce.nasa.gov
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: "acme-companion"
    networks:
      - rabbitmq_net
    restart: always
    depends_on:
      - nginx-proxy
    volumes_from:
      - nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme:/etc/acme.sh"
      - "./certs:/etc/nginx/certs:rw"
    environment:
      - DEFAULT_EMAIL=emmanuelgonzalez@asu.edu
      - FILES_PERMS=644
  keycloak:
    image: quay.io/keycloak/keycloak:20.0
    container_name: "keycloak"
    networks:
      - rabbitmq_net
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./conf/keycloak/import:/opt/keycloak/data/import
      - ./certs:/certs
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      # - LETSENCRYPT_TEST=true
    command: start --optimized --import-realm --hostname=nost.smce.nasa.gov --https-certificate-file=/certs/nost.smce.nasa.gov/fullchain.pem --https-certificate-key-file=/certs/nost.smce.nasa.gov/key.pem
  rabbitmq:
    image: rabbitmq:4.0.8-management
    container_name: "rabbitmq"
    networks:
      - rabbitmq_net
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5552:5552"
      - "15671:15671"
      - "5671:5671"
    volumes:
      - ./conf/keycloak:/conf
      - ./conf/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./conf/keycloak/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./conf/keycloak/advanced.config:/etc/rabbitmq/advanced.config:ro
      - ./certs:/certs
  rabbitmq_tcp_relay:
    image: cloudamqp/websocket-tcp-relay
    container_name: "rabbitmq_tcp_relay"
    networks:
      - rabbitmq_net
    restart: always
    ports:
      - "15670:15670"
    volumes:
      - ./conf/keycloak:/conf
      - ./certs:/certs
    environment:
    command: --upstream=tcp://rabbitmq:5672 --bind=0.0.0.0 --tls-cert=/certs/nost.smce.nasa.gov/fullchain.pem --tls-key=/certs/nost.smce.nasa.gov/key.pem
  nost-sos:
    image: emmanuelgonzalez/nost_sos_visualization:latest
    container_name: "nost-sos"
    networks:
      - rabbitmq_net
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ".env:/usr/src/app/.env"
    environment:
  nost-monitor-frontend:
    build:
      context: ../nost-monitor-frontend/
    container_name: "nost-monitor-frontend"
    networks:
      - rabbitmq_net
    restart: always
    expose:
      - "80"
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=nost.smce.nasa.gov
      - LETSENCRYPT_HOST=nost.smce.nasa.gov